subtitle: Ramblings about programming, Linux & Life
description: My dev blog
url: https://github.com/leogzyl/leogzyl.github.io

title: A Bit Curious
author: Leo Gzyl
email: leogzyl@yahoo.com

subscribe_rss: /atom.xml
simple_search: https://www.google.com/search
date_format: "ordinal"

root: /
permalink: /blog/:year/:month/:day/:title/


plugins: _plugins
sass_dir: _sass
code_dir: downloads/code
category_dir: blog/categories


markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    


highlighter: pygments
paginate_path: "posts/:num"
excerpt_link: "Read on &rarr;"
excerpt_separator: "<!--more-->"
recent_posts: 5
paginate: 10
titlecase: true

default_asides:
  - asides/recent_posts.html
  - asides/github.html
  - asides/delicious.html
  - asides/pinboard.html
  - asides/googleplus.html

exclude:
- Gemfile*
- Makefile
- Rakefile
- README.md

# blog_index_asides:
# post_asides:
# page_asides:

github_user: leogzyl
github_repo_count: 10
github_skip_forks: true
github_show_profile_link: true
disqus_show_comment_count: false
twitter_tweet_button: true
disqus_short_name: a-bit-curious
twitter_user: leogzyl
